name: docker

on:
  push:
    branches: [master] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: 139.9.212.113
          username: root
          password: ${{ secrets.PASS }}
          port: 22
          script: |
             cd /home/auto-answer-frontend/
             git pull
             docker stop auto-answer-frontend
             docker rm auto-answer-frontend
             docker rmi auto-answer-frontend
             docker build -t auto-answer-frontend .
             docker run -p 80:80 -d --name auto-answer-frontend auto-answer-frontend